### ISSUE TITLE
IDEA: Use LLVM as backend for compiled language.

### ISSUE THREAD

**Issue by lewek** [thecaketeam/u-programming-language#1]
@game-lover @thecakeisfalse 

If you want to make it compiled I recommended you to use LLVM as backend.

Also explore [U programming language](https://ulang.netlify.app/), u10 will be released soon.

**Comment by game-lover** [comment]
What do you want?

**Comment by lewek** [comment]
@game-lover 

I just want to get an idea to use LLVM as backend for your programming language.

**Comment by game-lover** [comment]
Why have you recommended me to explore U programming language and said about u10?

**Comment by enty8080** [comment]
@game-lover It uses LLVM as backend, I mean it will be compiled. This is just for example.

**Comment by lewek** [comment]
@game-lover It uses LLVM. This is just for example

**Comment by game-lover** [comment]
Why do you think that I should use LLVM?
